on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install deps
      run: |
        dnf -y install docker
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: wasp-companion.flatpak
        manifest-path: flatpak/io.github.siroj42.WaspCompanion.yml
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}
